# @package _global_



crop_size_list_: ??? # ! fixed most of the time
gta_scale_list_: ??? # ! change as crop_size

crop_size: &id002
  _args_:
  - ${crop_size_list_}
  _target_: builtins.tuple
gta_scale: &id004 
  _args_:
  - ${gta_scale_list_} # [1280, 720] if crop_size==[512, 512], [2560, 1440] if crop_size==[1024, 1024]
  _target_: builtins.tuple
city_scale:
  _args_:
  - [1280, 720]
  _target_: builtins.tuple



data_folder: /data
img_ratios: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
test_dataloader:
  batch_size: 2
  dataset:
    data_prefix:
      img_path: images/10k/val
      seg_map_path: labels/sem_seg/masks/val
    data_root: /data/BDD/
    pipeline:
    - type: LoadImageFromFile
    - keep_ratio: true
      scale: ${city_scale} # *id001
      type: Resize
    - type: LoadAnnotations
    - type: PackSegInputs
    type: BDD100KDataset
  num_workers: 2
  persistent_workers: true
  sampler:
    shuffle: false
    type: DefaultSampler
test_evaluator:
  iou_metrics:
  - mIoU
  type: IoUMetricWrapper

train_dataloader:
  batch_size: 2
  dataset:
    data_prefix:
      img_path: images
      seg_map_path: labels
    data_root: /data/GTA5
    pipeline:
    - type: LoadImageFromFile
    - type: LoadAnnotations
    - keep_ratio: true
      ratio_range: &id003
        _args_:
        - [0.5, 2.0]
        _target_: builtins.tuple
      scale: ${gta_scale}
      type: RandomResize
    - cat_max_ratio: 0.75
      crop_size: ${crop_size} # *id002
      type: RandomCrop
    - prob: 0.5
      type: RandomFlip
    - type: PhotoMetricDistortion
    - type: PackSegInputs
    type: GTADataset
  num_workers: 2
  persistent_workers: true
  sampler:
    shuffle: true
    type: InfiniteSampler
tta_pipeline:
  - backend_args: null
    type: LoadImageFromFile
  - transforms:
    - - keep_ratio: true
        scale_factor: 0.5
        type: Resize
      - keep_ratio: true
        scale_factor: 0.375
        type: Resize
      - keep_ratio: true
        scale_factor: 0.25
        type: Resize
      - keep_ratio: true
        scale_factor: 0.625
        type: Resize
      - keep_ratio: true
        scale_factor: 0.75
        type: Resize
      # - keep_ratio: true
      #   scale_factor: 0.875
      #   type: Resize
    # - - keep_ratio: true
    #     scale_factor: 0.5
    #     type: Resize
    #   - keep_ratio: true
    #     scale_factor: 0.75
    #     type: Resize
    #   - keep_ratio: true
    #     scale_factor: 1.0
    #     type: Resize
    #   - keep_ratio: true
    #     scale_factor: 1.25
    #     type: Resize
    #   - keep_ratio: true
    #     scale_factor: 1.5
    #     type: Resize
    #   - keep_ratio: true
    #     scale_factor: 1.75
    #     type: Resize
    - - direction: horizontal
        prob: 0.0
        type: RandomFlip
      # - direction: horizontal
      #   prob: 1.0
      #   type: RandomFlip
    - - type: LoadAnnotations
    - - type: PackSegInputs
    type: TestTimeAug

val_dataloader: ${test_dataloader}
val_evaluator: ${test_evaluator}
