# @package _global_
data_preprocessor:
  bgr_to_rgb: true
  mean: [123.675, 116.28, 103.53]
  pad_val: 0
  seg_pad_val: 255
  std: [58.395, 57.12, 57.375]
  type: SegDataPreProcessor
model:
  auxiliary_head:
  - align_corners: false
    channels: 16
    concat_input: false
    in_channels: 16
    in_index: 1
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 2
    type: FCNHead
  - align_corners: false
    channels: 64
    concat_input: false
    in_channels: 32
    in_index: 2
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 2
    type: FCNHead
  - align_corners: false
    channels: 256
    concat_input: false
    in_channels: 64
    in_index: 3
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 2
    type: FCNHead
  - align_corners: false
    channels: 1024
    concat_input: false
    in_channels: 128
    in_index: 4
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 2
    type: FCNHead
  backbone:
    align_corners: false
    bga_channels: 128
    detail_channels:
      _args_:
      - [64, 64, 128]
      _target_: builtins.tuple
    init_cfg: null
    out_indices:
      _args_:
      - [0, 1, 2, 3, 4]
      _target_: builtins.tuple
    semantic_channels:
      _args_:
      - [16, 32, 64, 128]
      _target_: builtins.tuple
    semantic_expansion_ratio: 6
    type: BiSeNetV2
  data_preprocessor:
    bgr_to_rgb: true
    mean: [123.675, 116.28, 103.53]
    pad_val: 0
    seg_pad_val: 255
    std: [58.395, 57.12, 57.375]
    type: SegDataPreProcessor
  decode_head:
    align_corners: false
    channels: 1024
    concat_input: false
    dropout_ratio: 0.1
    in_channels: 128
    in_index: 0
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 1
    type: FCNHead
  pretrained: null
  test_cfg:
    mode: whole
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  requires_grad: true
  type: SyncBN
