# @package _global_
defaults:
- daformer_conv1_mitb5.yaml
norm_cfg:
  requires_grad: true
  type: BN
model:
  decode_head:
    decoder_params:
      fusion_cfg:
        _delete_: true
        act_cfg:
          type: ReLU
        down_factor:
          _args_:
          - [8, 8]
          _target_: builtins.tuple
        isa_channels: 256
        key_query_num_convs: 1
        norm_cfg:
          requires_grad: true
          type: BN
        type: isa
