# @package _global_
data_preprocessor:
  bgr_to_rgb: true
  mean:
  - 123.675
  - 116.28
  - 103.53
  pad_val: 0
  seg_pad_val: 255
  std:
  - 58.395
  - 57.12
  - 57.375
  type: SegDataPreProcessor
model:
  auxiliary_head:
    align_corners: false
    channels: 64
    concat_input: false
    dropout_ratio: 0.1
    in_channels: 128
    in_index: 3
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 2
    num_convs: 1
    type: FCNHead
  backbone:
    act_cfg:
      type: ReLU
    base_channels: 64
    conv_cfg: null
    dec_dilations:
      _args_:
      - - 1
        - 1
        - 1
        - 1
      _target_: builtins.tuple
    dec_num_convs:
      _args_:
      - - 2
        - 2
        - 2
        - 2
      _target_: builtins.tuple
    downsamples:
      _args_:
      - - true
        - true
        - true
        - true
      _target_: builtins.tuple
    enc_dilations: &id001
      _args_:
      - - 1
        - 1
        - 1
        - 1
        - 1
      _target_: builtins.tuple
    enc_num_convs:
      _args_:
      - - 2
        - 2
        - 2
        - 2
        - 2
      _target_: builtins.tuple
    in_channels: 3
    norm_cfg:
      requires_grad: true
      type: SyncBN
    norm_eval: false
    num_stages: 5
    strides: *id001
    type: UNet
    upsample_cfg:
      type: InterpConv
    with_cp: false
  data_preprocessor:
    bgr_to_rgb: true
    mean:
    - 123.675
    - 116.28
    - 103.53
    pad_val: 0
    seg_pad_val: 255
    std:
    - 58.395
    - 57.12
    - 57.375
    type: SegDataPreProcessor
  decode_head:
    align_corners: false
    channels: 16
    dilations:
      _args_:
      - - 1
        - 12
        - 24
        - 36
      _target_: builtins.tuple
    dropout_ratio: 0.1
    in_channels: 64
    in_index: 4
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 2
    type: ASPPHead
  pretrained: null
  test_cfg:
    crop_size: 256
    mode: slide
    stride: 170
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  requires_grad: true
  type: SyncBN
