# @package _global_
data_preprocessor:
  bgr_to_rgb: true
  mean: [123.675, 116.28, 103.53]
  pad_val: 0
  seg_pad_val: 255
  std: [58.395, 57.12, 57.375]
  type: SegDataPreProcessor
model:
  auxiliary_head: null
  backbone:
    embed_dims: 768
    final_norm: false
    img_size: 224
    num_heads: 12
    num_layers: 12
    out_indices:
      _args_:
      - [2, 5, 8, 11]
      _target_: builtins.tuple
    output_cls_token: true
    type: VisionTransformer
    with_cls_token: true
  data_preprocessor:
    bgr_to_rgb: true
    mean: [123.675, 116.28, 103.53]
    pad_val: 0
    seg_pad_val: 255
    std: [58.395, 57.12, 57.375]
    type: SegDataPreProcessor
  decode_head:
    channels: 256
    embed_dims: 768
    in_channels:
      _args_:
      - [768, 768, 768, 768]
      _target_: builtins.tuple
    in_index:
      _args_:
      - [0, 1, 2, 3]
      _target_: builtins.tuple
    input_transform: multiple_select
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 150
    post_process_channels: [96, 192, 384, 768]
    readout_type: project
    type: DPTHead
  pretrained: pretrain/vit-b16_p16_224-80ecf9dd.pth
  test_cfg:
    mode: whole
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  requires_grad: true
  type: SyncBN
