# @package _global_
data_preprocessor:
  bgr_to_rgb: true
  mean: [123.675, 116.28, 103.53]
  pad_val: 0
  seg_pad_val: 255
  std: [58.395, 57.12, 57.375]
  type: SegDataPreProcessor
model:
  auxiliary_head:
  - align_corners: false
    channels: 32
    concat_input: false
    in_channels: 128
    in_index: -2
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: true
    norm_cfg:
      momentum: 0.01
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 1
    type: FCNHead
  - align_corners: false
    channels: 32
    concat_input: false
    in_channels: 64
    in_index: -3
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: true
    norm_cfg:
      momentum: 0.01
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 1
    type: FCNHead
  backbone:
    align_corners: false
    downsample_dw_channels:
      _args_:
      - [32, 48]
      _target_: builtins.tuple
    fusion_out_channels: 128
    global_block_channels:
      _args_:
      - [64, 96, 128]
      _target_: builtins.tuple
    global_block_strides:
      _args_:
      - [2, 2, 1]
      _target_: builtins.tuple
    global_in_channels: 64
    global_out_channels: 128
    higher_in_channels: 64
    lower_in_channels: 128
    norm_cfg:
      momentum: 0.01
      requires_grad: true
      type: SyncBN
    out_indices:
      _args_:
      - [0, 1, 2]
      _target_: builtins.tuple
    type: FastSCNN
  data_preprocessor:
    bgr_to_rgb: true
    mean: [123.675, 116.28, 103.53]
    pad_val: 0
    seg_pad_val: 255
    std: [58.395, 57.12, 57.375]
    type: SegDataPreProcessor
  decode_head:
    align_corners: false
    channels: 128
    concat_input: false
    in_channels: 128
    in_index: -1
    loss_decode:
      loss_weight: 1
      type: CrossEntropyLoss
      use_sigmoid: true
    norm_cfg:
      momentum: 0.01
      requires_grad: true
      type: SyncBN
    num_classes: 19
    type: DepthwiseSeparableFCNHead
  test_cfg:
    mode: whole
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  momentum: 0.01
  requires_grad: true
  type: SyncBN
