# @package _global_
data_preprocessor:
  bgr_to_rgb: true
  mean:
  - 123.675
  - 116.28
  - 103.53
  pad_val: 0
  seg_pad_val: 255
  std:
  - 58.395
  - 57.12
  - 57.375
  type: SegDataPreProcessor
model:
  auxiliary_head:
    align_corners: false
    channels: 256
    concat_input: false
    dropout_ratio: 0.1
    in_channels: 1024
    in_index: 2
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 1
    type: FCNHead
  backbone:
    contract_dilation: true
    depth: 50
    dilations:
      _args_:
      - - 1
        - 1
        - 2
        - 4
      _target_: builtins.tuple
    norm_cfg:
      requires_grad: true
      type: SyncBN
    norm_eval: false
    num_stages: 4
    out_indices:
      _args_:
      - - 0
        - 1
        - 2
        - 3
      _target_: builtins.tuple
    strides:
      _args_:
      - - 1
        - 2
        - 1
        - 1
      _target_: builtins.tuple
    style: pytorch
    type: ResNetV1c
  data_preprocessor:
    bgr_to_rgb: true
    mean:
    - 123.675
    - 116.28
    - 103.53
    pad_val: 0
    seg_pad_val: 255
    std:
    - 58.395
    - 57.12
    - 57.375
    type: SegDataPreProcessor
  decode_head:
    align_corners: false
    channels: 512
    dropout_ratio: 0.1
    in_channels: 2048
    in_index: 3
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    pool_scales:
      _args_:
      - - 1
        - 2
        - 3
        - 6
      _target_: builtins.tuple
    type: PSPHead
  pretrained: open-mmlab://resnet50_v1c
  test_cfg:
    mode: whole
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  requires_grad: true
  type: SyncBN
