# @package _global_
backbone_norm_cfg:
  eps: 1.0e-06
  requires_grad: true
  type: LN
data_preprocessor:
  bgr_to_rgb: true
  mean:
  - 123.675
  - 116.28
  - 103.53
  pad_val: 0
  seg_pad_val: 255
  std:
  - 58.395
  - 57.12
  - 57.375
  type: SegDataPreProcessor
model:
  auxiliary_head:
  - align_corners: false
    channels: 256
    concat_input: false
    dropout_ratio: 0
    in_channels: 256
    in_index: 0
    kernel_size: 1
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    num_classes: 19
    num_convs: 0
    type: FCNHead
  - align_corners: false
    channels: 256
    concat_input: false
    dropout_ratio: 0
    in_channels: 256
    in_index: 1
    kernel_size: 1
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    num_classes: 19
    num_convs: 0
    type: FCNHead
  - align_corners: false
    channels: 256
    concat_input: false
    dropout_ratio: 0
    in_channels: 256
    in_index: 2
    kernel_size: 1
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    num_classes: 19
    num_convs: 0
    type: FCNHead
  - align_corners: false
    channels: 256
    concat_input: false
    dropout_ratio: 0
    in_channels: 256
    in_index: 3
    kernel_size: 1
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    num_classes: 19
    num_convs: 0
    type: FCNHead
  backbone:
    drop_rate: 0.1
    embed_dims: 1024
    img_size:
      _args_:
      - - 768
        - 768
      _target_: builtins.tuple
    in_channels: 3
    interpolate_mode: bilinear
    norm_cfg:
      eps: 1.0e-06
      requires_grad: true
      type: LN
    num_heads: 16
    num_layers: 24
    out_indices:
      _args_:
      - - 5
        - 11
        - 17
        - 23
      _target_: builtins.tuple
    patch_size: 16
    type: VisionTransformer
    with_cls_token: false
  data_preprocessor:
    bgr_to_rgb: true
    mean:
    - 123.675
    - 116.28
    - 103.53
    pad_val: 0
    seg_pad_val: 255
    std:
    - 58.395
    - 57.12
    - 57.375
    type: SegDataPreProcessor
  decode_head:
    align_corners: false
    channels: 512
    dropout_ratio: 0
    in_channels:
      _args_:
      - - 256
        - 256
        - 256
        - 256
      _target_: builtins.tuple
    in_index:
      _args_:
      - - 0
        - 1
        - 2
        - 3
      _target_: builtins.tuple
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    mla_channels: 128
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    type: SETRMLAHead
  neck:
    act_cfg:
      type: ReLU
    in_channels:
    - 1024
    - 1024
    - 1024
    - 1024
    norm_cfg:
      requires_grad: true
      type: SyncBN
    out_channels: 256
    type: MLANeck
  pretrained: pretrain/jx_vit_large_p16_384-b3be5167.pth
  test_cfg:
    mode: whole
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  requires_grad: true
  type: SyncBN
