# @package _global_
backbone_norm_cfg:
  eps: 1.0e-06
  requires_grad: true
  type: LN
data_preprocessor:
  bgr_to_rgb: true
  mean: [123.675, 116.28, 103.53]
  pad_val: 0
  seg_pad_val: 255
  std: [58.395, 57.12, 57.375]
  type: SegDataPreProcessor
model:
  auxiliary_head:
  - align_corners: false
    channels: 256
    dropout_ratio: 0
    in_channels: 1024
    in_index: 0
    kernel_size: 3
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 1
    type: SETRUPHead
    up_scale: 4
  - align_corners: false
    channels: 256
    dropout_ratio: 0
    in_channels: 1024
    in_index: 1
    kernel_size: 3
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 1
    type: SETRUPHead
    up_scale: 4
  - align_corners: false
    channels: 256
    dropout_ratio: 0
    in_channels: 1024
    in_index: 2
    kernel_size: 3
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 1
    type: SETRUPHead
    up_scale: 4
  backbone:
    drop_rate: 0.1
    embed_dims: 1024
    img_size:
      _args_:
      - [768, 768]
      _target_: builtins.tuple
    in_channels: 3
    interpolate_mode: bilinear
    norm_cfg:
      eps: 1.0e-06
      requires_grad: true
      type: LN
    num_heads: 16
    num_layers: 24
    out_indices:
      _args_:
      - [9, 14, 19, 23]
      _target_: builtins.tuple
    patch_size: 16
    type: VisionTransformer
    with_cls_token: true
  data_preprocessor:
    bgr_to_rgb: true
    mean: [123.675, 116.28, 103.53]
    pad_val: 0
    seg_pad_val: 255
    std: [58.395, 57.12, 57.375]
    type: SegDataPreProcessor
  decode_head:
    align_corners: false
    channels: 256
    dropout_ratio: 0
    in_channels: 1024
    in_index: 3
    kernel_size: 3
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 4
    type: SETRUPHead
    up_scale: 2
  pretrained: pretrain/jx_vit_large_p16_384-b3be5167.pth
  test_cfg:
    mode: whole
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  requires_grad: true
  type: SyncBN
