# @package _global_
data_preprocessor:
  bgr_to_rgb: true
  mean: [123.675, 116.28, 103.53]
  pad_val: 0
  seg_pad_val: 255
  std: [58.395, 57.12, 57.375]
  type: SegDataPreProcessor
model:
  auxiliary_head:
  - align_corners: false
    channels: 64
    concat_input: false
    in_channels: 128
    in_index: 2
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: BN
    num_classes: 19
    num_convs: 1
    sampler:
      min_kept: 10000
      thresh: 0.7
      type: OHEMPixelSampler
    type: FCNHead
  - align_corners: false
    channels: 64
    concat_input: false
    in_channels: 128
    in_index: 1
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: BN
    num_classes: 19
    num_convs: 1
    sampler:
      min_kept: 10000
      thresh: 0.7
      type: OHEMPixelSampler
    type: FCNHead
  - align_corners: true
    boundary_threshold: 0.1
    channels: 64
    concat_input: false
    in_channels: 256
    in_index: 0
    loss_decode:
    - loss_name: loss_ce
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: true
    - loss_name: loss_dice
      loss_weight: 1.0
      type: DiceLoss
    norm_cfg:
      requires_grad: true
      type: BN
    num_classes: 2
    num_convs: 1
    type: STDCHead
  backbone:
    backbone_cfg:
      act_cfg:
        type: ReLU
      bottleneck_type: cat
      channels:
        _args_:
        - [32, 64, 256, 512, 1024]
        _target_: builtins.tuple
      in_channels: 3
      norm_cfg:
        requires_grad: true
        type: BN
      num_convs: 4
      stdc_type: STDCNet1
      type: STDCNet
      with_final_conv: false
    ffm_cfg:
      in_channels: 384
      out_channels: 256
      scale_factor: 4
    last_in_channels:
      _args_:
      - [1024, 512]
      _target_: builtins.tuple
    out_channels: 128
    type: STDCContextPathNet
  data_preprocessor:
    bgr_to_rgb: true
    mean: [123.675, 116.28, 103.53]
    pad_val: 0
    seg_pad_val: 255
    std: [58.395, 57.12, 57.375]
    type: SegDataPreProcessor
  decode_head:
    align_corners: true
    channels: 256
    concat_input: false
    dropout_ratio: 0.1
    in_channels: 256
    in_index: 3
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: BN
    num_classes: 19
    num_convs: 1
    sampler:
      min_kept: 10000
      thresh: 0.7
      type: OHEMPixelSampler
    type: FCNHead
  pretrained: null
  test_cfg:
    mode: whole
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  requires_grad: true
  type: BN
