# @package _global_
backbone_norm_cfg:
  requires_grad: true
  type: LN
data_preprocessor:
  bgr_to_rgb: true
  mean:
  - 123.675
  - 116.28
  - 103.53
  pad_val: 0
  seg_pad_val: 255
  std:
  - 58.395
  - 57.12
  - 57.375
  type: SegDataPreProcessor
model:
  auxiliary_head:
    align_corners: false
    channels: 256
    concat_input: false
    dropout_ratio: 0.1
    in_channels: 384
    in_index: 2
    loss_decode:
      loss_weight: 0.4
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    num_convs: 1
    type: FCNHead
  backbone:
    act_cfg:
      type: GELU
    attn_drop_rate: 0.0
    depths:
    - 2
    - 2
    - 6
    - 2
    drop_path_rate: 0.3
    drop_rate: 0.0
    embed_dims: 96
    mlp_ratio: 4
    norm_cfg:
      requires_grad: true
      type: LN
    num_heads:
    - 3
    - 6
    - 12
    - 24
    out_indices:
      _args_:
      - - 0
        - 1
        - 2
        - 3
      _target_: builtins.tuple
    patch_norm: true
    patch_size: 4
    pretrain_img_size: 224
    qk_scale: null
    qkv_bias: true
    strides:
      _args_:
      - - 4
        - 2
        - 2
        - 2
      _target_: builtins.tuple
    type: SwinTransformer
    use_abs_pos_embed: false
    window_size: 7
  data_preprocessor:
    bgr_to_rgb: true
    mean:
    - 123.675
    - 116.28
    - 103.53
    pad_val: 0
    seg_pad_val: 255
    std:
    - 58.395
    - 57.12
    - 57.375
    type: SegDataPreProcessor
  decode_head:
    align_corners: false
    channels: 512
    dropout_ratio: 0.1
    in_channels:
    - 96
    - 192
    - 384
    - 768
    in_index:
    - 0
    - 1
    - 2
    - 3
    loss_decode:
      loss_weight: 1.0
      type: CrossEntropyLoss
      use_sigmoid: false
    norm_cfg:
      requires_grad: true
      type: SyncBN
    num_classes: 19
    pool_scales:
      _args_:
      - - 1
        - 2
        - 3
        - 6
      _target_: builtins.tuple
    type: UPerHead
  pretrained: null
  test_cfg:
    mode: whole
  train_cfg: {}
  type: EncoderDecoder
norm_cfg:
  requires_grad: true
  type: SyncBN
