defaults:
  - src2cityscapes.yaml

train_dataloader:
  dataset:
    data_prefix:
      img_path: RGB
      seg_map_path: GT/LABELS
    data_root: /data/synthia
    type: SynthiaDataset
    pipeline:
      - type: LoadImageFromFile
      - type: LoadAnnotations
      - keep_ratio: true
        ratio_range: &id003
          _args_:
          - [0.5, 2.0]
          _target_: builtins.tuple
        scale: ${gta_scale}
        type: RandomResize
      - cat_max_ratio: 0.75
        crop_size: ${crop_size} # *id002
        type: RandomCrop
      - prob: 0.5
        type: RandomFlip
      - type: PhotoMetricDistortion
      - type: PackSegInputs
