# @package _global_
defaults:
- ./cityscapes.yaml
crop_size: &id001
  _args_:
  - [769, 769]
  _target_: builtins.tuple
train_pipeline:
- type: LoadImageFromFile
- type: LoadAnnotations
- keep_ratio: true
  ratio_range: &id003
    _args_:
    - [0.5, 2.0]
    _target_: builtins.tuple
  scale: &id002
    _args_:
    - [2049, 1025]
    _target_: builtins.tuple
  type: RandomResize
- cat_max_ratio: 0.75
  crop_size: *id001
  type: RandomCrop
- prob: 0.5
  type: RandomFlip
- type: PhotoMetricDistortion
- type: PackSegInputs
test_pipeline:
- type: LoadImageFromFile
- keep_ratio: true
  scale: *id002
  type: Resize
- type: LoadAnnotations
- type: PackSegInputs
train_dataloader:
  dataset:
    pipeline:
    - type: LoadImageFromFile
    - type: LoadAnnotations
    - keep_ratio: true
      ratio_range: *id003
      scale: *id002
      type: RandomResize
    - cat_max_ratio: 0.75
      crop_size: *id001
      type: RandomCrop
    - prob: 0.5
      type: RandomFlip
    - type: PhotoMetricDistortion
    - type: PackSegInputs
val_dataloader:
  dataset:
    pipeline:
    - type: LoadImageFromFile
    - keep_ratio: true
      scale: *id002
      type: Resize
    - type: LoadAnnotations
    - type: PackSegInputs
test_dataloader:
  dataset:
    pipeline:
    - type: LoadImageFromFile
    - keep_ratio: true
      scale: *id002
      type: Resize
    - type: LoadAnnotations
    - type: PackSegInputs
val_evaluator:
  iou_metrics:
  - mIoU
  type: IoUMetric
test_evaluator:
  iou_metrics:
  - mIoU
  type: IoUMetric
