# @package _global_
crop_size: &id002
  _args_:
  - [512, 512]
  _target_: builtins.tuple
data_root: data/REFUGE
dataset_type: REFUGEDataset
img_ratios: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
test_dataloader:
  batch_size: 1
  dataset:
    data_prefix:
      img_path: images/test
      seg_map_path: annotations/test
    data_root: data/REFUGE
    pipeline:
    - type: LoadImageFromFile
    - keep_ratio: true
      scale: &id001
        _args_:
        - [1634, 1634]
        _target_: builtins.tuple
      type: Resize
    - reduce_zero_label: false
      type: LoadAnnotations
    - type: PackSegInputs
    type: REFUGEDataset
  num_workers: 4
  persistent_workers: true
  sampler:
    shuffle: false
    type: DefaultSampler
test_evaluator:
  iou_metrics:
  - mDice
  type: IoUMetric
test_img_scale: *id001
test_pipeline:
- type: LoadImageFromFile
- keep_ratio: true
  scale: *id001
  type: Resize
- reduce_zero_label: false
  type: LoadAnnotations
- type: PackSegInputs
train_dataloader:
  batch_size: 4
  dataset:
    data_prefix:
      img_path: images/training
      seg_map_path: annotations/training
    data_root: data/REFUGE
    pipeline:
    - type: LoadImageFromFile
    - reduce_zero_label: false
      type: LoadAnnotations
    - keep_ratio: true
      ratio_range: &id004
        _args_:
        - [0.5, 2.0]
        _target_: builtins.tuple
      scale: &id003
        _args_:
        - [2056, 2124]
        _target_: builtins.tuple
      type: RandomResize
    - cat_max_ratio: 0.75
      crop_size: *id002
      type: RandomCrop
    - prob: 0.5
      type: RandomFlip
    - type: PhotoMetricDistortion
    - type: PackSegInputs
    type: REFUGEDataset
  num_workers: 4
  persistent_workers: true
  sampler:
    shuffle: true
    type: InfiniteSampler
train_img_scale: *id003
train_pipeline:
- type: LoadImageFromFile
- reduce_zero_label: false
  type: LoadAnnotations
- keep_ratio: true
  ratio_range: *id004
  scale: *id003
  type: RandomResize
- cat_max_ratio: 0.75
  crop_size: *id002
  type: RandomCrop
- prob: 0.5
  type: RandomFlip
- type: PhotoMetricDistortion
- type: PackSegInputs
tta_pipeline:
- backend_args:
    backend: local
  type: LoadImageFromFile
- transforms:
  - - keep_ratio: true
      scale_factor: 0.5
      type: Resize
    - keep_ratio: true
      scale_factor: 0.75
      type: Resize
    - keep_ratio: true
      scale_factor: 1.0
      type: Resize
    - keep_ratio: true
      scale_factor: 1.25
      type: Resize
    - keep_ratio: true
      scale_factor: 1.5
      type: Resize
    - keep_ratio: true
      scale_factor: 1.75
      type: Resize
  - - direction: horizontal
      prob: 0.0
      type: RandomFlip
    - direction: horizontal
      prob: 1.0
      type: RandomFlip
  - - type: LoadAnnotations
  - - type: PackSegInputs
  type: TestTimeAug
val_dataloader:
  batch_size: 1
  dataset:
    data_prefix:
      img_path: images/validation
      seg_map_path: annotations/validation
    data_root: data/REFUGE
    pipeline:
    - type: LoadImageFromFile
    - keep_ratio: true
      scale: *id001
      type: Resize
    - reduce_zero_label: false
      type: LoadAnnotations
    - type: PackSegInputs
    type: REFUGEDataset
  num_workers: 4
  persistent_workers: true
  sampler:
    shuffle: false
    type: DefaultSampler
val_evaluator:
  iou_metrics:
  - mDice
  type: IoUMetric
val_img_scale: *id001
val_pipeline:
- type: LoadImageFromFile
- keep_ratio: true
  scale: *id001
  type: Resize
- reduce_zero_label: false
  type: LoadAnnotations
- type: PackSegInputs
